### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by Sharpie360** [dennybiasiolli/react-vuex#22]
What is the status of this project, interested in using in a production application built in react-native. The app will be ported over to a Vue mobile frontend when other projects reach maturity required. What are the plans for this project? Are there any maintainers?

Thank you!

**Comment by dennybiasiolli** [comment]
Hi Sean, actually I'm the mantainer of this project, it's intended as a "bridge" between React components and Vuex state manager, and works similarly to Redux

**Comment by Sharpie360** [comment]
Cool! Thank you for the prompt response! :)
