### ISSUE TITLE
Connected components try to update state after being unmounted

### ISSUE THREAD

**Issue by KosnIre** [dennybiasiolli/react-vuex#24]
FYI, I've also created PR #25 to address this issue. Below is a more detailed explanation of what's happening.

## Environment
- `"react": "^16.7.0"`
- `"react-vuex": "^0.2.1"`
- `"vuex": "^3.1.0"`

## Expected behavior
- React components should not update state after being unmounted.

## Actual behavior
- A component that uses the `react-vuex` `connect()` API attempts to continue updating its state after being unmounted from the DOM.

When a connected component unmounts from the DOM and then the store is updated, the component's state is still updated even though it doesn't need to be.

React detects this and generates the following error:

```shell
  console.error node_modules/react-dom/cjs/react-dom.development.js:506
    Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

### In action
1. Create a connected component with `react-vuex`'s `connect()` API. Make sure to subscribe to a store state item or a getter. Mount this to the DOM.
2. Unmount the connected component from the DOM (in practice, this could be a screen change, or a variety of different actions).
3. `commit` some mutation to the store. React will log the above error to the console.

### With unit tests
In `connect.spec.js`, simply add the `component.unmount()` call at the end of each unit test to complete the normal React lifecycle. The tests near the bottom ("real store mutations") do store updates so they show the error with this call in place.

## Root cause
In `connect.js`, `react-vuex` uses the `vuex` API `store.subscribe()` to keep the component updated with store changes. This part works great. The problem is that the component never unsubscribes from the changes. Fortunately, `vuex` provides us with a simple API to do so, returned by `subscribe()`.

## Fix
Please review my PR #25  for a potential fix to this issue.

**Comment by dennybiasiolli** [comment]
Thanks @KosnIre for this awesome PR, I'm reviewing the code, adding some tests and then I will merge it into the master branch

**Comment by KosnIre** [comment]
Excellent :smile: Thanks for the quick turn-around @dennybiasiolli . And thanks for putting together this repo too. It's just what I needed at the moment.
