### ISSUE TITLE
Managing to update the vuex store between the time of the constructor and componentDidMount, the component will not receive the change

### ISSUE THREAD

**Issue by dennybiasiolli** [dennybiasiolli/react-vuex#28]
Thanks to @Kosnire for the detailed explanation

### Issue summary

If you manage to update the vuex store between the time of the constructor and `componentDidMount`, the component will not receive the change.

I guess I made a poor assumption based on [the React docs for componentDidMount](https://reactjs.org/docs/react-component.html#componentdidmount):

> This method is a good place to set up any subscriptions. If you do that, don’t forget to unsubscribe in componentWillUnmount().

Sorry about that :slightly_frowning_face: 

### Reproducing

In my case, I'm trying make a `commit()` during the `componentDidMount` method of my component that is already `connect()`'d with the `react-vuex` API. The screen did not update as I expected. I added some logs and was eventually able to confirm the order of events:

1. The `componentDidMount()` method that I added to MyComponent is called.
2. The MyComponent method makes a commit to the vuex store.
3. `mapStateToProps` is called for every other component _except_ the one I'm expecting.
4. The `componentDidMount()` method in the `connect` HOC is called.
5. The HOC method subscribes to the vuex store.
5. MyComponent renders visually without the updated data.

### Potential fix

I see 2 options for a fix:

A. Go back to doing the `subscribe()` in the `constructor()` like you had it before. Still save the `unscubscribe()` method and call it during `componentWillUnmount()`. --OR--
B. Run an additional check to see if the state or getters have changed at the top of `componentDidMount()`, **then** subscribe to the vuex store changes. Still save the `unscubscribe()` method and call it during `componentWillUnmount()`.

I have tested that A has fixed my issue locally (have not tested B). A seems simpler to me, but I want to see what you think is the best option, or if you have another idea.

_Originally posted by @KosnIre in https://github.com/dennybiasiolli/react-vuex/pull/25#issuecomment-498455409_

**Comment by KosnIre** [comment]
New release works great. Thanks again :smiley:
